tabs:
  fields:
    # Header settings
    logo:
      label: Логотип 
      tab: Header
      type: mediafinder 
      mode: image

    header_menu:
      label: Меню
      type: repeater
      tab: Header
      prompt: Додати пункт меню
      form:
        fields:
          label: 
            label: Назва
            type: text
            span: left
          url:
            label: Посилання
            type: text
            span: right
    

    # Footer settings
    company_name:
      tab: Footer
      span: left
      label: Company name
    company_description:
      tab: Footer
      span: left
      label: Company description
      type: textarea
      size: small
    contact_phone:
      tab: Footer
      span: left
      label: Contact phone
      type: text
    contact_address:
      tab: Footer
      span: left
      label: Contact address
      type: text
    contact_email:
      tab: Footer
      span: left
      label: Contact email
      type: text
    copyright:
      tab: Footer
      span: left
      label: Copyright
      type: text
    # Social links
    social_links: 
      label: Соціальні мережі
      type: repeater
      tab: Social Links
      prompt: Додати соціальну мережу
      form:
        fields:
          label:
            label: Назва
            type: text
            span: left
          url:
            label: Посилання
            type: text
            span: right


    # Index page
    main_slider:
      tab: Main slider
      span: full
      label: Main slider
      type: repeater
      form:
        fields:
          title:
            span: left
            label: lovata.toolbox::lang.field.title
            type: text
          image:
            span: right
            label: lovata.toolbox::lang.field.image
            type: mediafinder
            mode: image
          link:
            span: left
            label: lovata.toolbox::lang.field.link
            type: text
          link_name:
            span: left
            label: Link name
            type: text
          description:
            span: full
            label: lovata.toolbox::lang.field.description
            type: textarea
            size: small
    extend_field:
      tab: Index page
      span: left
      type: partial
      path: ~/themes/lovata-bootstrap-shopaholic/config/_extend_field.htm
    promo_block_left:
      tab: Index page
      span: left
      label: Left promo block
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'
    promo_block_middle:
      tab: Index page
      span: left
      label: Middle promo block
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'
    promo_block_right:
      tab: Index page
      span: left
      label: Right promo block
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'
    index_banner:
      span: left
      tab: Index page
      label: Banner image
      type: mediafinder
      mode: image
    index_banner_link:
      span: left
      tab: Index page
      label: Banner image link
      type: text
    category_left:
      tab: Index page
      span: left
      label: Left category
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'
    category_middle:
      tab: Index page
      span: left
      label: Middle category
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'
    category_right:
      tab: Index page
      span: left
      label: Right category
      type: dropdown
      emptyOption: 'lovata.toolbox::lang.field.empty'